# This file contains values from Cookiecutter

default_context:
  project_name: "epigraphhub"
  project_description: "Epigraphhub Python package"
  organization: "thegraphnetwork"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.9
  github_name: "thegraphnetwork"
  email: "fccoelho@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
